### PR TITLE
Test code review tools

### PR DESCRIPTION
**Pull request by WhatWouldHoneyBadgerDo**
@tysonshaw New review.  Please make comments and/or find issues.

---
This change is [Reviewable](https://reviewable.io/reviews/whatwouldhoneybadgerdo/hello-world/6)

### CODE REVIEW

**Comment by tysonshaw** [comment]
*[README.md, line 4 at r1](https://reviewable.io:443/reviews/whatwouldhoneybadgerdo/hello-world/6#-KW-bi23MEkyAuPIFlby:-KW-bi23MEkyAuPIFlbz:b-q1f80a) ([raw file](https://github.com/whatwouldhoneybadgerdo/hello-world/blob/7f57b81c0698ca1d8361c82c9d39d92500cbf512/README.md#L4)):*
> ```Markdown
> This is the requisite Hello World project.
> 
> It greets the world.
> ```

Need more languages now!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/whatwouldhoneybadgerdo/hello-world/6)*

**Comment by tysonshaw** [comment]
This is unacceptable!

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/whatwouldhoneybadgerdo/hello-world/6#-:-KW-cUcsu2nGGDCo-upS:banh11p)*

**Comment by WhatWouldHoneyBadgerDo** [comment]
FYI, you have high standards.  :)   (I think if I start comment with FYI or BTW, it doesn't require a response or acknowledgment from you in order to consider the discussion complete.  Is that how it is working for you?  You don't have to acknowledge this comment, but you do have to acknowledge the comment about languages?)

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 4 at r1](https://reviewable.io:443/reviews/whatwouldhoneybadgerdo/hello-world/6#-KW-bi23MEkyAuPIFlby:-KW-cK3OaopPEnyBEOIG:b-23y18k) ([raw file](https://github.com/whatwouldhoneybadgerdo/hello-world/blob/7f57b81c0698ca1d8361c82c9d39d92500cbf512/README.md#L4)):*
<details><summary><i>Previously, tysonshaw wrote…</i></summary>
> Need more languages now!
</details>
Spanish, Chinese, and Arabic will all be supported next week.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/whatwouldhoneybadgerdo/hello-world/6#-:-KW-cvIgKJpFf9r3P_AY:bzcblsy)*

**Comment by tysonshaw** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/whatwouldhoneybadgerdo/hello-world/6)*

**Pull request merged**
